kind = "DojoContract"
class_hash = "0xe5cbb94c3fa9cd137b5ca208877170f96819048222ce23c89ab026ae117b63"
original_class_hash = "0xe5cbb94c3fa9cd137b5ca208877170f96819048222ce23c89ab026ae117b63"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/dojo_starter_systems_actions_actions.json"
reads = []
writes = []
computed = []
name = "dojo_starter::systems::actions::actions"
